# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Esog8YDaSmAMqkqhmMOWVgiz68Lhz0t
"""

from modelo import Perfil, Carreira, Competencia

def inicializar_dados():
    """Define as competências e carreiras disponíveis no sistema."""

    # Lista de Competências (Uso de Lista)
    competencias_disponiveis = [
        Competencia("Logica", "tecnica", "Capacidade de resolver problemas de forma estruturada."),
        Competencia("Criatividade", "comportamental", "Habilidade de gerar ideias originais."),
        Competencia("Colaboracao", "comportamental", "Trabalho eficaz em equipe e comunicação."),
        Competencia("Adaptabilidade", "comportamental", "Facilidade em lidar com mudanças e aprender rápido."),
        Competencia("Analise Dados", "tecnica", "Interpretação e manipulação de conjuntos de dados.")
    ]

    # Tupla de Objetos Carreira (Uso de Tupla)
    # Requisitos usam Dicionários
    carreiras_do_futuro = (
        Carreira(
            "Cientista de Dados",
            {'logica': 1.0, 'analise dados': 1.0, 'adaptabilidade': 0.6, 'colaboracao': 0.5, 'criatividade': 0.2,}
        ),
        Carreira(
            "Desenvolvedor Full-Stack",
            {'logica': 0.9, 'adaptabilidade': 0.9, 'colaboracao': 0.8, 'analise dados': 0.3, 'criatividade': 0.5,}
        ),
        Carreira(
            "Designer UX/UI",
            {'criatividade': 1.0, 'colaboracao': 0.7, 'adaptabilidade': 0.6, 'logica': 0.4, 'analise dados': 0.2,}
        ),
        Carreira(
            "Especialista em Cibersegurança",
            {'logica': 1.0, 'analise dados': 0.7, 'adaptabilidade': 0.8, 'colaboracao': 0.4, 'criatividade': 0.2,}
        )
    )

    return competencias_disponiveis, carreiras_do_futuro


def main():
    """Função principal para executar a aplicação."""
    competencias, carreiras = inicializar_dados()

    print("--- Orientação de Carreiras ---")
    nome_usuario = input("Digite seu nome: ")
    meu_perfil = Perfil(nome_usuario)

    # Coleta de Dados via CLI
    print("\n Autoavaliação de Competências (Nota de 1 a 5)")
    for comp in competencias:
        print(f"-> {comp.exibir_detalhes()}")
        while True:
            try:
                # Coleta a pontuação do usuário
                pontuacao = int(input(f"    Sua nota para {comp.nome}: "))
                if 1 <= pontuacao <= 5:
                    meu_perfil.cadastrar_competencia(comp.nome, pontuacao)
                    break
                else:
                    print("Digite uma nota entre 1 e 5.")
            except ValueError:
                print("Entrada inválida. Digite um número inteiro.")

    # Processamento e Geração de Recomendações
    print("\n--- 📈 Resultados da Análise de Perfil ---")
    recomendacoes = []

    for carreira in carreiras:
        aderencia = carreira.avaliar_aderencia(meu_perfil)
        recomendacoes.append((aderencia, carreira.nome))

    # Ordena as recomendações do maior para o menor
    recomendacoes.sort(key=lambda x: x[0], reverse=True)

    print(f"Olá, {meu_perfil.nome}! Suas 3 melhores recomendações de carreira são:")
    for aderencia, nome_carreira in recomendacoes[:3]:
        print(f"* **{nome_carreira}**: Aderência de **{aderencia:.2f}%**")

    # Geração de Recomendações de Aprimoramento (Condicional) [cite: 9, 16]
    print("\n--- Trilhas de Aprimoramento Sugeridas ---")
    # Encontra a competência com a pontuação mais baixa
    comp_baixa = min(meu_perfil.competencias, key=meu_perfil.competencias.get)
    pontuacao_baixa = meu_perfil.competencias[comp_baixa]

    if pontuacao_baixa < 3:
        print(f"Sua pontuação mais baixa é em **{comp_baixa.capitalize()}** ({pontuacao_baixa}).")
        print(f"Recomendamos focar em aprimorar **{comp_baixa.capitalize()}** para fortalecer seu perfil!")

        if comp_baixa == 'logica' or comp_baixa == 'analise dados':
            print("> **Ação Sugerida:** Trilhas de aprendizado em Raciocínio Algorítmico e Estruturas de Dados.")
        elif comp_baixa == 'criatividade':
            print("> **Ação Sugerida:** Cursos sobre Design Thinking, Inovação e Geração de Ideias.")
        elif comp_baixa == 'colaboracao' or comp_baixa == 'adaptabilidade':
            print("> **Ação Sugerida:** Treinamentos em Soft Skills, Comunicação e Gestão de Mudanças.")
    else:
        print("Seu perfil é bem equilibrado! Continue investindo em desenvolvimento contínuo.")

if __name__ == "__main__":
    main()