# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10Esog8YDaSmAMqkqhmMOWVgiz68Lhz0t
"""

class Competencia:
    """Representa uma competência profissional, podendo ser técnica ou comportamental."""
    def __init__(self, nome, tipo, descricao):
        self.nome = nome
        # Tipo pode ser: 'tecnica' ou 'comportamental'
        self.tipo = tipo
        self.descricao = descricao

    def exibir_detalhes(self):
        """Retorna os detalhes formatados da competência."""
        return f"Competência: {self.nome} | Tipo: {self.tipo.capitalize()} | Descrição: {self.descricao}"


class Perfil:
    """Representa o perfil de um usuário e suas pontuações em competências."""
    def __init__(self, nome):
        self.nome = nome
        # Dicionário: {'competencia_nome_lower': pontuacao (1-5)}
        # Cumpre o requisito de usar dicionários para armazenar dados [cite: 8, 14]
        self.competencias = {}

    def cadastrar_competencia(self, nome, pontuacao):
        """Adiciona ou atualiza uma pontuação de competência, garantindo que seja entre 1 e 5."""
        # Garante que a pontuação esteja dentro do limite (1 a 5)
        pontuacao = max(1, min(5, pontuacao))
        # Armazena a chave em minúsculas para padronização
        self.competencias[nome.lower()] = pontuacao
        print(f"Competência '{nome}' cadastrada com pontuação {pontuacao}.")


class Carreira:
    """Define uma carreira e as competências essenciais (pesos) para ela."""
    def __init__(self, nome, requisitos):
        self.nome = nome
        # Dicionário: {'competencia_nome_lower': peso (0.0 a 1.0)}
        self.competencias_requeridas = requisitos

    def avaliar_aderencia(self, perfil):
        """
        Calcula a pontuação de aderência do perfil à carreira (função),
        usando média ponderada e aplicando penalidade em competências essenciais baixas (condicional).
        """
        pontuacao_total = 0.0
        peso_total = sum(self.competencias_requeridas.values())

        for comp, peso in self.competencias_requeridas.items():
            # Obtém a pontuação do perfil, se não tiver, assume 1 (mínimo)
            pontuacao_do_perfil = perfil.competencias.get(comp, 1)

            # 1. Cálculo Base (Média Ponderada)
            contribuicao = pontuacao_do_perfil * peso
            pontuacao_total += contribuicao

            # 2. Lógica de Penalidade (Condicional para recomendação)
            # Se a competência for ESSENCIAL (peso >= 0.8) E a nota for MUITO BAIXA (< 2),
            # o sistema aplica uma penalidade na pontuação total.
            if peso >= 0.8 and pontuacao_do_perfil < 2:
                # Redução de 15% na contribuição total.
                pontuacao_total *= 0.85

        # Normaliza a pontuação final para uma porcentagem (0 a 100%)
        if peso_total > 0:
            aderencia = (pontuacao_total / peso_total) / 5 * 100
        else:
            aderencia = 0

        return max(0, aderencia) # Garante que o resultado final seja não-negativo